version: 2.1

orbs:
    win: circleci/windows@2.2.0

jobs:
    build-linux:
        docker:
            - image: perl:5.10.1
        working_directory: /App-Rakubrew
        steps:
            - checkout
            - run:
                name: Run build script
                command: release-stuff/build-linux.sh
            - store_artifacts:
                path: rakubrew
                destination: rakubrew-perl
    build-macos:
        macos:
            xcode: 11.3.1
        steps:
            - run:
                name: Install Perl
                command: brew install perl
            - run:
                name: Install cpanm
                command: brew install cpanminus
            - checkout
            - run:
                name: Run build script
                command: release-stuff/build-macos.sh
            - store_artifacts:
                path: rakubrew
                destination: rakubrew-macos
    build-windows:
        executor: win/default
        working_directory: C:\App-Rakubrew
        steps:
            - checkout
            - run:
                name: Run build script
                command: release-stuff/build-windows.ps1
            - store_artifacts:
                path: rakubrew.exe
                destination: rakubrew-windows.exe

workflows:
    version: 2
    build-release:
        jobs:
            - build-linux:
                filters:
                    tags:
                        only: /\n+/
            - build-macos:
                filters:
                    tags:
                        only: /\n+/
            - build-windows:
                filters:
                    tags:
                        only: /\n+/

