version: 2.1

orbs:
    win: circleci/windows@2.2.0

parameters:
  MANUAL_BUILD:
    type: boolean
    default: false

jobs:
    build-linux:
        docker:
            - image: perl:5.10.1
        working_directory: /App-Rakubrew
        steps:
            - checkout
            - run:
                name: Run build script
                command: release-stuff/build-linux.sh
            - run: mv rakubrew rakubrew-perl
            - store_artifacts:
                path: rakubrew-perl
                destination: rakubrew-perl
            - persist_to_workspace:
                root: .
                paths: rakubrew-perl
    build-macos:
        macos:
            xcode: 11.3.1
        steps:
            - run:
                name: Install Perl
                command: brew install perl
            - run:
                name: Install cpanm
                command: brew install cpanminus
            - checkout
            - run:
                name: Run build script
                command: release-stuff/build-macos.sh
            - run: mv rakubrew rakubrew-macos
            - store_artifacts:
                path: rakubrew-macos
                destination: rakubrew-macos
            - persist_to_workspace:
                root: .
                paths: rakubrew-macos
    build-windows:
        executor: win/default
        working_directory: C:\App-Rakubrew
        steps:
            - checkout
            - run:
                name: Run build script
                command: release-stuff/build-windows.ps1
            - run: mv rakubrew.exe rakubrew-windows.exe
            - store_artifacts:
                path: rakubrew-windows.exe
                destination: rakubrew-windows.exe

            - persist_to_workspace:
                root: .
                paths: rakubrew-windows.exe
    zip-results:
        docker:
            - image: alpine
        steps:
            - attach_workspace:
                at: workspace
            - run:
                working_directory: workspace
                command: |
                    mkdir $CIRCLE_TAG
                    mkdir $CIRCLE_TAG/perl
                    mv rakubrew-perl $CIRCLE_TAG/perl/rakubrew
                    mkdir $CIRCLE_TAG/win
                    mv rakubrew-windows.exe $CIRCLE_TAG/win/rakubrew.exe
                    mkdir $CIRCLE_TAG/macos
                    mv rakubrew-macos $CIRCLE_TAG/macos/rakubrew
                    tar -czf rakubrew.tgz $CIRCLE_TAG
            - store_artifacts:
                path: workspace/rakubrew.tgz
                destination: rakubrew.tgz

workflows:
    version: 2
    build-release:
        jobs:
            - build-linux:
                filters:
                    tags:
                        only: /\n+/
                    branches:
                        ignore: /.*/
            - build-macos:
                filters:
                    tags:
                        only: /\n+/
                    branches:
                        ignore: /.*/
            - build-windows:
                filters:
                    tags:
                        only: /\n+/
                    branches:
                        ignore: /.*/
            - zip-results:
                requires:
                    - build-linux
                    - build-macos
                    - build-windows
                filters:
                    tags:
                        only: /\n+/
                    branches:
                        ignore: /.*/

    manual-build:
        when: << pipeline.parameters.MANUAL_BUILD >>
        jobs:
            - build-linux:
            - build-macos:
            - build-windows:
            - zip-results:
                requires:
                    - build-linux
                    - build-macos
                    - build-windows

