version: 2
jobs:
    build-linux:
        docker:
            - image: perl:5.10.1
        working_directory: /work
        steps:
            - checkout
            - run: release-stuff/build-linux.sh
            - store_artifacts:
                path: rakubrew
                destination: rakubrew-perl
workflows:
    version: 2
    build-release:
        jobs:
            - build-linux:
                filters:
                    tags:
                        only: /\n+/
